TechDays_Lesson_1/Models/AdVm.cs
namespace TechDays_Lesson_1.Models
{
    public class AdVm
    {
        #region Properties

        public string Name { get; set; }

        public string Root { get; set; }

        public string Sub { get; set; }

        #endregion
    }
}

TechDays_Lesson_1/Models/AddAdCommand.cs
namespace TechDays_Lesson_1.Models
{
    public class AddAdCommand
    {
        #region Properties

        public string Name { get; set; }

        public string Root { get; set; }

        public string Sub { get; set; }

        #endregion
    }
}

TechDays_Lesson_1/Models/SearchAdQuery.cs
namespace TechDays_Lesson_1.Models
{
    public class SearchAdQuery
    {
        #region Properties

        public string Root { get; set; }

        public string Sub { get; set; }

        #endregion
    }
}

TechDays_Lesson_1/Controllers/AdController.cs
namespace TechDays_Lesson_1.Controllers
{
    #region << Using >>

    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Incoding.MvcContrib;
    using TechDays_Lesson_1.Models;

    #endregion

    public class AdController : Controller
    {
        #region Static Fields

        static List<AdVm> ads = new List<AdVm>();

        #endregion

        #region Http action

        [HttpPost]
        public ActionResult Add(AddAdCommand command)
        {
            ads.Add(new AdVm
                        {
                                Name = command.Name,
                                Root = command.Root,
                                Sub = command.Sub
                        });
            return IncodingResult.Success();
        }

        [HttpPost]
        public ActionResult Del(string name)
        {
            int index = ads.FindIndex(r => r.Name == name);
            ads.RemoveAt(index);
            return IncodingResult.Success();
        }

        [HttpGet]
        public ActionResult Fetch(SearchAdQuery query)
        {
            return IncodingResult.Success(ads.Where(r => string.IsNullOrWhiteSpace(query.Root) || r.Root == query.Root)
                                             .Where(r => string.IsNullOrWhiteSpace(query.Sub) || r.Sub == query.Sub));
        }

        [HttpPost]
        public ActionResult RemoveAll()
        {
            ads = new List<AdVm>();
            return IncodingResult.Success();
        }

        #endregion
    }
}

TechDays_Lesson_1/Controllers/CategoryController.cs
namespace TechDays_Lesson_1.Controllers
{
    #region << Using >>

    using System.Collections.Generic;
    using System.Web.Mvc;
    using Incoding.MvcContrib;

    #endregion

    public class CategoryController : Controller
    {
        #region Http action

        [HttpGet]
        public ActionResult FetchRoot()
        {
            var vms = new List<KeyValueVm>
                          {
                                  new KeyValueVm("Cars"), 
                                  new KeyValueVm("Houses"), 
                                  new KeyValueVm("Electronics"), 
                          };
            return IncodingResult.Success(vms);
        }

        [HttpGet]
        public ActionResult FetchSub(string root)
        {
            var vms = new Dictionary<string, List<KeyValueVm>>
                          {
                                  {
                                          "Cars", new List<KeyValueVm>
                                                      {
                                                              new KeyValueVm("Coupe"), 
                                                              new KeyValueVm("Jeep"), 
                                                              new KeyValueVm("Sedan"), 
                                                      }
                                  }, 
                                  {
                                          "Houses", new List<KeyValueVm>
                                                        {
                                                                new KeyValueVm("Rooms"), 
                                                                new KeyValueVm("Apartments"), 
                                                        }
                                  }, 
                                  {
                                          "Electronics", new List<KeyValueVm>
                                                             {
                                                                     new KeyValueVm("Phones"), 
                                                                     new KeyValueVm("Computers"), 
                                                             }
                                  }, 
                          };
            return IncodingResult.Success(vms[root]);
        }

        #endregion
    }
}

TechDays_Lesson_1/Controllers/HomeController.cs
namespace TechDays_Lesson_1.Controllers
{
    #region << Using >>

    using System.Web.Mvc;

    #endregion

    public class HomeController : Controller
    {
        #region Http action

        [HttpGet]
        public ActionResult Iml()   
        {
            return View();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Jquery()
        {
            return View();
        }

        #endregion
    }
}

TechDays_Lesson_1/Views/Home/IML.cshtml
@using Incoding.Extensions
@using Incoding.MvcContrib
@model AddAdCommand
<html>
    <head>                
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.8.3.min.js")"> </script>      
        <script type="text/javascript" src="@Url.Content("~/Scripts/underscore.min.js")"> </script>      
        <script type="text/javascript" src="@Url.Content("~/Scripts/mustache.js")"> </script>              
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.history.js")"> </script>              
        <script type="text/javascript" src="@Url.Content("~/Scripts/incoding.framework.js")"> </script>      
    </head>
    <body>
        
        @{
            string containerId = Guid.NewGuid().ToString();
            string tmplId = Guid.NewGuid().ToString();
            using (var template = Html.Incoding().ScriptTemplate<KeyValueVm>(tmplId))
            {
                using (var each = template.ForEach())
                {
                    <option value="@each.For(r => r.Value)">
                        @each.For(r => r.Text)
                    </option>
                }
            }
        }

        <div>
            <label>Name</label>
            @Html.TextBoxFor(r => r.Name)
        </div>
        <div>
            <label>Root</label>
            @Html.DropDownListFor(r => r.Root, new SelectList(new string[0]), Html.When(JqueryBind.InitIncoding)
                                                                                  .Do()
                                                                                  .AjaxGet(Url.Action("FetchRoot", "Category"))
                                                                                  .OnSuccess(dsl =>
                                                                                                 {
                                                                                                     dsl.Self().Core().Insert.WithTemplate(Selector.Jquery.Id(tmplId)).Html();
                                                                                                     dsl.Self().Core().Trigger.Invoke(JqueryBind.Change);
                                                                                                 })
                                                                                  .When(JqueryBind.Change)
                                                                                  .Do()
                                                                                  .Direct()
                                                                                  .OnSuccess(dsl => dsl.With(r => r.Id<AddAdCommand>(s => s.Sub)).Core().Trigger.Incoding())
                                                                                  .AsHtmlAttributes())
        </div>
        <div>
            <label>Sub</label>
            @Html.DropDownListFor(r => r.Sub, new SelectList(new string[0]), Html.When(JqueryBind.None)
                                                                                 .Do()
                                                                                 .AjaxGet(Url.Action("FetchSub", "Category", new
                                                                                                                                 {
                                                                                                                                         root = Selector.Jquery.Id<AddAdCommand>(r => r.Root)
                                                                                                                                 }))
                                                                                 .OnSuccess(dsl => dsl.Self().Core().Insert.WithTemplate(Selector.Jquery.Id(tmplId)).Html())
                                                                                 .AsHtmlAttributes())
        </div>
        <div>
            @(Html.When(JqueryBind.Click)
                  .Do()
                  .Direct()
                  .OnSuccess(dsl => dsl.With(r => r.Id<AddAdCommand>(s => s.Name)
                                                   .Add(selector => selector.Id<AddAdCommand>(s => s.Root)))
                                       .Behaviors(inDsl =>
                                                      {
                                                          inDsl.Core().JQuery.Attributes.Val("");
                                                          inDsl.Core().Trigger.Invoke(JqueryBind.Change);
                                                      }))
                  .AsHtmlAttributes()
                  .ToButton("Clear"))
            @(Html.When(JqueryBind.Click)
                  .Do()
                  .AjaxPost(Url.Action("Add", "Ad", new AddAdCommand
                                                        {
                                                                Name = Selector.Jquery.Id<AddAdCommand>(r => r.Name),
                                                                Root = Selector.Jquery.Id<AddAdCommand>(r => r.Root),
                                                                Sub = Selector.Jquery.Id<AddAdCommand>(r => r.Sub),
                                                        }))
                  .OnSuccess(dsl => dsl.With(r => r.Id(containerId)).Core().Trigger.Incoding())
                  .AsHtmlAttributes()
                  .ToButton("Add")) 
        </div>
        
        @{
            string tabelTmplId = Guid.NewGuid().ToString();
            using (var template = Html.Incoding().ScriptTemplate<AdVm>(tabelTmplId))
            {
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Root</th>
                            <th>Sub</th>
                            <th></th>
                        </tr>
                    </thead>       
                    <tbody>
                        @using (var each = template.ForEach())
                        {
                            <tr>
                                <td>@each.For(r => r.Name)</td>
                                <td>@each.For(r => r.Root)</td>
                                <td>@each.For(r => r.Sub)</td>
                                <td>
                                    @(Html.When(JqueryBind.Click)
                                          .DoWithPreventDefault()
                                          .AjaxPost(HttpUtility.UrlDecode(Url.Action("Del", "Ad", new { name = each.For(r => r.Name) })))
                                          .OnBegin(dsl => dsl.Self().Core().Break.If(builder => builder.Not.Confirm("Are sure delete {0}".F(each.For(r => r.Name)))))
                                          .OnSuccess(dsl => dsl.With(r => r.Self().Closest(selector => selector.Tag(HtmlTag.Tr))).Core().JQuery.Manipulation.Remove())
                                          .AsHtmlAttributes()
                                          .ToLink("Del"))
                                </td>
                            </tr>
                        }
                    </tbody>            
                </table>
            }
        }


        @(Html.When(JqueryBind.InitIncoding | JqueryBind.IncChangeUrl)
              .Do()
              .AjaxHashGet(Url.Action("Fetch", "Ad"))
              .OnSuccess(dsl => dsl.Self().Core().Insert.WithTemplate(Selector.Jquery.Id(tabelTmplId)).Html())
              .AsHtmlAttributes(new { id = containerId })
              .ToDiv())
        
        
        @(Html.When(JqueryBind.Click)
              .Do()
              .AjaxPost(Url.Action("RemoveAll", "Ad"))
              .OnSuccess(dsl => dsl.With(r => r.Id(containerId)).Core().Trigger.Incoding())
              .AsHtmlAttributes()
              .ToButton("Remove All"))
    </body>
</html>

TechDays_Lesson_1/Views/Home/Index.cshtml
<html>
    <body>
        <ul>
            <li>
                <a href="@Url.Action("Jquery")">Jquery</a>                
            </li>
            <li>
                <a href="@Url.Action("IML")">IML</a>
            </li>
        </ul>
    </body>
</html>

TechDays_Lesson_1/Views/Home/Jquery.cshtml
@model AddAdCommand
<html>
    <head>                
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.8.3.min.js")"> </script>                
        <script>
            $(document).ready(function() {
                
                var initAdTable = function() {

                    $.get('@Url.Action("Fetch", "Ad")', function(result) {
                        $('#tbodyAdTable').empty();
                        $(result.data).each(function() {
                            var tr = $("<tr>")
                                .append($('<td>').html(this.Name))
                                .append($('<td>').html(this.Root))
                                .append($('<td>').html(this.Sub));

                            $('#tbodyAdTable').append(tr);
                        });
                    });

                };

                $('#Root').change(function() {                    
                    $.get('@Url.Action("FetchSub", "Category")', { root: $('#Root').val() }, function (result) {
                        $('#Sub').empty();
                        $(result.data).each(function() {
                            var option = $('<option>').attr({
                                value : this.Value
                            }).text(this.Text);
                            $('#Sub').append(option);
                        });
                    });
                });
                                
                $.get('@Url.Action("FetchRoot", "Category")', function(result) {
                    $('#Root').empty();
                    $(result.data).each(function() {
                        var option = $('<option>').attr({
                            value : this.Value
                        }).text(this.Text);
                        $('#Root').append(option);
                    });
                    $('#Root').change();
                });


                $('#btnAdd').click(function () {
                    $.post('@Url.Action("Add", "Ad")', {
                            name : $('#Name').val(),
                            root : $('#Root').val(),
                            sub : $('#Sub').val()
                        }, function() {
                            initAdTable();
                        });
                });

                $('#btnClear').click(function() {
                    $('#Root,#Name')
                        .val('')
                        .change();
                });

                $('#btnRemoveAll').click(function() {
                    $.post('@Url.Action("RemoveAll", "Ad")', function() {
                        initAdTable();
                    });
                });

                initAdTable();
            });
        </script>
    </head>    
    <body>
        
        <div>
            <label>
                Name
            </label>
            @Html.TextBoxFor(r => r.Name)
        </div>
        <div>
            <label>Root</label>
            @Html.DropDownListFor(r => r.Root, new SelectList(new string[0]))
        </div>
        <div>
            <label>Sub</label>
            @Html.DropDownListFor(r => r.Sub, new SelectList(new string[0]))
        </div>
        <button id="btnClear">Clear form</button>
        <button id="btnAdd">Add</button>
        
        <div>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Root</th>
                        <th>Sub</th>
                    </tr>
                </thead>
                <tbody id="tbodyAdTable">                    
                </tbody>
            </table>
            <button id="btnRemoveAll">Remove all data</button>
        </div>
    </body>    
</html>